import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
const inter = Inter({ subsets: ['latin'] })
import DisplayGallery from '../components/DisplayGallery'

export default function Home() {
	return (
		<>
		<Head>
			<title>Welcome To Zoll & Meter</title>
			<meta name="description" content="Generated by create next app" />
			<meta name="viewport" content="width=device-width, initial-scale=1" />
			<link rel="icon" href="/zmlogo.png" />
		</Head>
		<main className={`${styles.homepage}`}>
			{/* <h1 className={`${styles.heading} ${styles.text}`}>ZOLL & METER</h1> */}
			<div className={`${styles.box} ${styles.row}`}>
				<Image className={`${styles.img0}`} src="/img0.webp" alt="cloth" width="1150" height="550"/>
			</div>
			<DisplayGallery></DisplayGallery>
			
		</main>
		</>
	)
}
